### PR TITLE
[Feature] Tests added

### PR DESCRIPTION
**Pull request by AngieArlanti**
# Changes
Tests added or corrected for:

- ConnectivityVerifier.h 
- DirectedClusteringCoefficient.h 
- DirectedNearestNeighborsDegree.h
- DirectedVertexAspect.h (Tests added and methods corrected: addIncomingEdge() wasn't responding as expected)
- MaxClique.h
- WeightedBetweenness.h
- StrengthDistribution.h 
- WeightedGraphTest.cpp (Corrected)

### CODE REVIEW

**Comment by federicobond** [comment]
LGTM, but there are some conflicts to resolve before merging.

**Comment by AngieArlanti** [comment]
Thanks! we dont see conflicts, @federicobond do you mean after merging "Command line improvements" PR?

**Comment by federicobond** [comment]
Ah ok, those conflicts are only for rebasing apparently, which is what I have set as default for merging.

**Comment by ihameli** [comment]
Many thanks federico!

  o
 ,N` 
 / \

**Pull request merged**
